Fix 'Failed to set up'
Fix construction of the AlertsDataUpdateCoordinator to use the
ConfigEntry instead of config.data. This fixes a 'Failed to set up'
message, with the detailed logs containing an AttributeError
('mappingproxy' object has no attribute 'async_on_unload').

Fixes #117.